export const TORRENT_FIELDS = [
  'activityDate',
  'addedDate',
  'bandwidthPriority',
  'comment',
  'corruptEver',
  'creator',
  'dateCreated',
  'desiredAvailable',
  'doneDate',
  'downloadDir',
  'downloadedEver',
  'downloadLimit',
  'downloadLimited',
  'editDate',
  'error',
  'errorString',
  'eta',
  'etaIdle',
  'file',
  'files',
  'fileStats',
  'hashString',
  'haveUnchecked',
  'haveValid',
  'honorsSessionLimits',
  'id',
  'isFinished',
  'isPrivate',
  'isStalled',
  'labels',
  'leftUntilDone',
  'magnetLink',
  'manualAnnounceTime',
  'maxConnectedPeers',
  'metadataPercentComplete',
  'name',
  'peer',
  'peers',
  'peersConnected',
  'peersFrom',
  'peersGettingFromUs',
  'peersSendingToUs',
  'percentDone',
  'pieces',
  'pieceCount',
  'pieceSize',
  'priorities',
  'primary',
  'queuePosition',
  'rateDownload',
  'rateUpload',
  'recheckProgress',
  'secondsDownloading',
  'secondsSeeding',
  'seedIdleLimit',
  'seedIdleMode',
  'seedRatioLimit',
  'seedRatioMode',
  'sizeWhenDone',
  'startDate',
  'status',
  'trackers',
  'trackerStats',
  'totalSize',
  'torrentFile',
  'uploadedEver',
  'uploadLimit',
  'uploadLimited',
  'uploadRatio',
  'wanted',
  'webseeds',
  'webseedsSendingToUs'
];

export enum QUEUE {
    TOP = 'top',
    UP = 'up',
    DOWN = 'down',
    BOTTOM = 'bottom'
}

export enum PRIORITY {
    LOW,
    NORMAL,
    HIGH
}